Repository MiroslavLuckai/PA165-Monster-Slayer-Agency, pull requests merged in 2020-04, with the labels that each got.

#36 Use case diagram updated
  documentation/use-case-diagram.jpg
Labels: documentation

#38 Job service
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/JobService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/JobServiceImpl.java
Labels: completed, review needed

#45 Creating request service and implementation
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestServiceImpl.java
Labels: completed, review needed

#44 Creating mapping service and configuration
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/BeanMappingService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/BeanMappingServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/config/ServiceConfiguration.java
Labels: completed, review needed

#46 Monster DTO and Facade
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/MonsterCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/MonsterDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/MonsterFacade.java
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/MonsterFacadeImpl.java
Labels: completed

#40 JobDTO and JobCreateDTO
  msa-api/pom.xml
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/JobCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/JobDTO.java
Labels: review needed

#39 Time service
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/JobServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/TimeService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/TimeServiceImpl.java
Labels: completed

#49 Request test use Enitity Manager and log4j is logging now
  msa-persistence/pom.xml
  msa-persistence/src/test/java/cz/muni/fi/pa165/monsterslayeragency/dao/RequestTest.java
  msa-persistence/src/test/resources/log4j.properties
Labels: completed, review needed

#41 JobFacade and JobFacadeImpl
  msa-api/pom.xml
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/JobCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/JobDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/RequestCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/RequestDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/JobFacade.java
  msa-service/pom.xml
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/JobFacadeImpl.java
Labels: review needed

#55 Created class for dummy objects
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/DummyObjects.java
Labels: completed, enhancement, review needed

#53 Request facade implementation
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/JobDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/RequestDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/RequestFacade.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/RequestFacadeImpl.java
Labels: completed, review needed

#52 Beanmapping test
  msa-api/pom.xml
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/entities/Hero.java
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/entities/User.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/BeanMappingServiceImplTest.java
Labels: completed

#59 hero service and facade done
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/HeroFacade.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/HeroFacadeImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/JobFacadeImpl.java
Labels: review needed

#58 Edited UserService and UserServiceImpl
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserServiceImpl.java
Labels: waiting-for-merge

#63 Fixes
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/RequestFacade.java
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/entities/Request.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/RequestFacadeImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/BeanMappingServiceImplTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/RequestServiceImplTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/RequestFacadeImplTest.java
Labels: completed, review needed

#60 JobService tests
  msa-service/pom.xml
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/JobServiceTests.java
Labels: review needed

#62 Created MonsterServiceImplTest
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterServiceImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/MonsterServiceImplTest.java
Labels: review needed

#64 Hero service,facade test
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/HeroFacade.java
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/dao/HeroDao.java
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/dao/HeroDaoImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/HeroFacadeImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/HeroServiceTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/HeroFacadeTest.java
Labels: review needed

#66 Monster facade tests
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/MonsterCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/MonsterFacade.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/UserFacade.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/MonsterFacadeImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/UserFacadeImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/MonsterFacadeImplTest.java
Labels: review needed

#61 Throwing exceptions
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/HeroServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/JobServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/MonsterServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/utils/Validator.java
Labels: waiting-for-merge

#65 JobFacade tests
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/JobFacadeImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/UserFacadeImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/DummyObjects.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/JobFacadeTest.java
Labels: review needed

#68 fixed failing tests
  msa-persistence/src/main/java/cz/muni/fi/pa165/monsterslayeragency/dao/MonsterDaoImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/MonsterServiceImplTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/RequestServiceImplTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/JobFacadeTest.java
Labels: review needed

#67 Request facade tests
  msa-api/src/main/java/cz/muni/fi/pa165/msa/dto/RequestCreateDTO.java
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/RequestFacade.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestService.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/RequestServiceImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/RequestServiceImplTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/RequestFacadeImplTest.java
Labels: review needed

#69 User service and facade tests added
  msa-api/src/main/java/cz/muni/fi/pa165/msa/facade/UserFacade.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/UserServiceImpl.java
  msa-service/src/main/java/cz/muni/fi/pa165/msa/service/facade/UserFacadeImpl.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/UserServiceTest.java
  msa-service/src/test/java/cz/muni/fi/pa165/msa/service/facade/UserFacadeTest.java
Labels: review needed
